name: Pipeline Calculadora

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  security:
    runs-on: ubuntu-latest  
    steps:   
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Rodar Coverage
        run: npm run coverage
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Verificar vulnerabilidades
        run: npm audit --audit-level=high 
      
      - name: Cache de Dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  quality:
    runs-on: ubuntu-latest
    needs: security
  
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Rodar Coverage
        run: npm run coverage
      
      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Zamengoo_teste
            -Dsonar.organization=zamengoo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Cache de Dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  build:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Gerar artefato
        run: zip -r app.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip
      
      - name: Cache de Dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: login no docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zamengo/calc:latest

  test:
    needs: build

    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar Dependências
        run: npm install

      - name: Rodar Testes
        run: npm test

      - name: Cache de Dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: login no docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: rodar testes dentro do container
        run: docker run zamengo/calc:latest npm test